# D-tale Module 
Particularly, we will be able to explore and wrangle your datasets via the graphical point-and-click interface. Here's what you can do: 
- import and export data; 
- sort, filter, format data; 
- create plots such as histograms, heatmaps, scatter plots, box plots, network analysis, etc.

In [24]:
import dtale
import pandas as pd
from pycaret.datasets import get_data # for import datasets
import warnings
warnings.filterwarnings("ignore")

In [17]:
df = get_data('wine')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [18]:
d = dtale.show(df)
d

- Code export from dtale tab on browser, and it works

In [22]:

import numpy as np
import pandas as pd

if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
    df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

corr_cols = [
'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
'pH', 'sulphates', 'alcohol', 'quality'
]
corr_data = np.corrcoef(df[corr_cols].values, rowvar=False)
corr_data = pd.DataFrame(corr_data, columns=[corr_cols], index=[corr_cols])
corr_data.index.name = str('column')
corr_data = corr_data.reset_index()

In [23]:
corr_data

,level_0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,fixed acidity,1.000000,0.219008,0.324436,-0.111981,0.298195,-0.282735,-0.329054,0.458910,-0.252700,0.299568,-0.095452,-0.076743
1,volatile acidity,0.219008,1.000000,-0.377981,-0.196011,0.377124,-0.352557,-0.414476,0.271296,0.261454,0.225984,-0.037640,-0.265699
2,citric acid,0.324436,-0.377981,1.000000,0.142451,0.038998,0.133126,0.195242,0.096154,-0.329808,0.056197,-0.010493,0.085532
3,residual sugar,-0.111981,-0.196011,0.142451,1.000000,-0.128940,0.402871,0.495482,0.552517,-0.267320,-0.185927,-0.359415,-0.036980
4,chlorides,0.298195,0.377124,0.038998,-0.128940,1.000000,-0.195045,-0.279630,0.362615,0.044708,0.395593,-0.256916,-0.200666
5,free sulfur dioxide,-0.282735,-0.352557,0.133126,0.402871,-0.195045,1.000000,0.720934,0.025717,-0.145854,-0.188457,-0.179838,0.055463
6,total sulfur dioxide,-0.329054,-0.414476,0.195242,0.495482,-0.279630,0.720934,1.000000,0.032395,-0.238413,-0.275727,-0.265740,-0.041385
7,density,0.458910,0.271296,0.096154,0.552517,0.362615,0.025717,0.032395,1.000000,0.011686,0.259478,-0.686745,-0.305858
8,pH,-0.252700,0.261454,-0.329808,-0.267320,0.044708,-0.145854,-0.238413,0.011686,1.000000,0.192123,0.121248,0.019506
9,sulphates,0.299568,0.225984,0.056197,-0.185927,0.395593,-0.188457,-0.275727,0.259478,0.192123,1.000000,-0.003029,0.038485
10,alcohol,-0.095452,-0.037640,-0.010493,-0.359415,-0.256916,-0.179838,-0.265740,-0.686745,0.121248,-0.003029,1.000000,0.444319
11,quality,-0.076743,-0.265699,0.085532,-0.036980,-0.200666,0.055463,-0.041385,-0.305858,0.019506,0.038485,0.444319,1.000000

In [30]:
# main statistics
stats = df['fixed acidity'].describe().to_frame().T
# sum
stats['sum'] = df['fixed acidity'].sum()
# median
stats['median'] = df['fixed acidity'].median()
# mode
mode = df['fixed acidity'].mode().values
stats['mode'] = np.nan if len(mode) > 1 else mode[0]
# var
stats['var'] = df['fixed acidity'].var()
# sem
stats['sem'] = df['fixed acidity'].sem()
uniq_vals = df['fixed acidity'].value_counts().sort_values(ascending=False)
uniq_vals.index.name = 'value'
uniq_vals.name = 'count'
uniq_vals = uniq_vals.reset_index()
uniq_vals.loc[:, 'type'] = 'float64'
sequential_diffs = df['fixed acidity'].diff()
#diff = diff[diff == diff]
min_diff = sequential_diffs.min()
max_diff = sequential_diffs.max()
avg_diff = sequential_diffs.mean()
diff_vals = sequential_diffs.value_counts().sort_values(ascending=False)

In [34]:
stats

,count,mean,std,min,25%,50%,75%,max,sum,median,mode,var,sem
fixed acidity,6497.0,7.215307,1.296434,3.8,6.4,7.0,7.7,15.9,46877.85,7.0,6.8,1.68074,0.016084

# Conclusion 

You can perform dtale functionality own your notebook. I enjoyed when i apply something on it. I will add some Screenshots in file, but you can follow links below and get experiment.

Links about dtale:

- Data professor youtube https://www.youtube.com/watch?v=jYlwwNycVh8&t=11s
- dtale PyPI https://pypi.org/project/dtale/​
- dtale GitHub https://github.com/man-group/dtale​
- dtale live demo http://alphatechadmin.pythonanywhere.com/dtale/main/1